# For use with VSCode plugin: REST Client 
# Available here: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = http://localhost:3000/api

# @name createSession
POST {{baseUrl}}/createSession HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "username": "steve"
}

####

@session = {{createSession.response.body.token}}

####

# @name createItem
POST {{baseUrl}}/items  HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{session}}

{
  "name": "The name",
  "description": "This is the description of this item.",
  "price": 10
}

####

DELETE {{baseUrl}}/items/{{getItems.response.body.$[0].id}}
Accept: application/json
Authorization: Bearer {{session}}

####

GET {{baseUrl}}/items/{{createItem.response.body.$.id}}
Accept: application/json
Authorization: Bearer {{session}}

####

# @name getItems
GET {{baseUrl}}/items
Authorization: Bearer {{session}}
Accept: application/json

###

@itemId = {{createItem.response.body.$.id}}

GET {{baseUrl}}/items/{{itemId}}
Accept: application/json
Authorization: Bearer {{session}}

####

GET {{baseUrl}}/items/{{createItem.response.body.$.id}}
Accept: application/json
Authorization: Bearer {{session}}

####

# @name createTask
POST {{baseUrl}}/items/10/actions HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{session}}

{
  "action": "DELAY"
}

####

# @name createTask
POST {{baseUrl}}/items/10/actions-oneOf HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{session}}

{
  "action": "WAIT",
  "length": 1000
}

####

# @name createTask
POST {{baseUrl}}/items/foo/actions-oneOf HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{session}}

{
  "action": "HOLD",
  "duration": 3000
}

####

# @name createTask
POST {{baseUrl}}/items/10/actions-oneOf HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{session}}

{
  "action": "PAUSE",
  "seconds": 3000
}

####

@taskId = {{createTask.response.body.$.id}}

GET {{baseUrl}}/tasks/{{taskId}}
Accept: application/json
Authorization: Bearer {{session}}

####


GET https://docs.vmware.com/en/VMware-Cloud-Director/10.3/VMware-Cloud-Director-Install-Configure-Upgrade-Guide/GUID-66221D98-FA64-43EF-B6DF-5C2CED29FE6A.html

