@baseUrl = http://localhost:3000/api

# @name createSession
POST {{baseUrl}}/createSession HTTP/1.1
Content-Type: application/json

{
  "username": "steve"
}

####

@session = {{createSession.response.body.session}}

####

# @name createItem
POST {{baseUrl}}/items  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{session}}

{
  "name": "The name",
  "description": "This is the description of this item.",
  "price": 10
}

####

DELETE {{baseUrl}}/items/59
Authorization: Bearer {{session}}

####

GET {{baseUrl}}/items/{{createItem.response.body.$.id}}
Authorization: Bearer {{session}}

####

# @name getItems
GET {{baseUrl}}/items
Authorization: Bearer {{session}}
Accept: application/json

###

@itemId = {{createItem.response.body.$.id}}

GET {{baseUrl}}/items/{{itemId}}
Authorization: Bearer {{session}}

